import type { Metadata } from "next";
import { Geist, Geist_Mono, DM_Sans, Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import 'leaflet/dist/leaflet.css';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const dmSans = DM_Sans({
  subsets: ["latin"],
  weight: ['400', '500', '600'],
  variable: "--font-dm-sans",
});

const plusJakarta = Plus_Jakarta_Sans({ 
  subsets: ['latin'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={plusJakarta.className}>
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0" />
        {/* ...existing head content... */}
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${dmSans.variable}`}
      >
        {children}
      </body>
    </html>
  );
}